version: "3.9"

services:

  mysql:
    image: mysql:8.4
    container_name: medflow-mysql

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: medflow
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    ports:
      - "3306:3306"

    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:7

    container_name: medflow-redis

    ports:
      - "6379:6379"

volumes:
  mysql-data: