spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO}
    open-in-view: false

gemini:
  api-key: ${GEMINI_API_KEY}
  model: ${GEMINI_MODEL}

ai:
  provider: ${AI_PROVIDER}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method
  api-docs:
    path: /v3/api-docs

jwt:
  secret: ${JWT_SECRET}